### ISSUE TITLE
Pass parameters for migration

### ISSUE THREAD

**Issue by AndreyIlin** [hubrick/elasticsearch-migration#3]
Is there an ability to use some placeholders in yaml changeset and then pass parameters during migration?
The case is that I need to read index names from zookeeper and for each of them create index. So index names may vary depending on environment, so I need a way to use placeholder in changeset and  then pass index name as parameter for migration.

**Comment by eemmiirr** [comment]
Technically it is of course but then we would have a dynamic changeset which changes based on environment which basicaly destroy the purpose of such a tool.

**Comment by AndreyIlin** [comment]
In my case it makes sense, because I need to create similar indexes with similar mappings but with different names and all changes like mapping update should be reflected on all of those. 

I'll probably workaround this by generating composite yaml changeset witch will contain operations for each index name from my configuration based on some common template.

Thanks.
